DROP VIEW IF EXISTS HostingDepartmentProgramme CASCADE;
DROP VIEW IF EXISTS Hosting CASCADE;
DROP VIEW IF EXISTS NotHostingDepartmentProgramme CASCADE;
DROP VIEW IF EXISTS NotHosting CASCADE;
DROP VIEW IF EXISTS StudentsAttendingProgramme CASCADE;

DROP VIEW IF EXISTS PathToGraduation CASCADE;
DROP VIEW IF EXISTS UnreadMandatory CASCADE;
DROP VIEW IF EXISTS PassedCourses CASCADE;
DROP VIEW IF EXISTS Registrations CASCADE;
DROP VIEW IF EXISTS FinishedCourses CASCADE;
DROP VIEW IF EXISTS StudentsFollowing CASCADE;

-- in backwards order since psql complains
-- about tables depending on other tables
DROP TABLE IF EXISTS Finished CASCADE;
DROP TABLE IF EXISTS Registered CASCADE;
DROP TABLE IF EXISTS Recommended CASCADE;
DROP TABLE IF EXISTS BranchMandatory CASCADE;
DROP TABLE IF EXISTS ProgrammeMandatory CASCADE;
DROP TABLE IF EXISTS Prerequisite CASCADE;
DROP TABLE IF EXISTS WaitingOn CASCADE;
DROP TABLE IF EXISTS HasClass CASCADE;
DROP TABLE IF EXISTS Classifications CASCADE;
DROP TABLE IF EXISTS LimitedCourses CASCADE;
DROP TABLE IF EXISTS ChosenBranch CASCADE;
DROP TABLE IF EXISTS Students CASCADE;
DROP TABLE IF EXISTS Courses CASCADE;
DROP TABLE IF EXISTS Branches CASCADE;
DROP TABLE IF EXISTS HostedBy CASCADE;
DROP TABLE IF EXISTS Programmes CASCADE;
DROP TABLE IF EXISTS Departments CASCADE;
